compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_reg: 0.46695720506953253
  n_lags: 28
  reg_lambda: 4.669572050695325e-05
config_events: !!python/object/apply:collections.OrderedDict
- - - covid_1
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: null
      upper_window: 0
  - - covid_2
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: null
      upper_window: 0
  - - covid_3
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: null
      upper_window: 0
  - - covid_4
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: null
      upper_window: 0
  - - Labor
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: multiplicative
      reg_lambda: null
      upper_window: 0
  - - Lunar
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: multiplicative
      reg_lambda: null
      upper_window: 0
  - - Summer
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: multiplicative
      reg_lambda: null
      upper_window: 0
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id003 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 252374400000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1420070400000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          /v////ORAEE=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AQAAAAAAAAA=
    - - deaths
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAABAW0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - cases
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          wczMzIw8ykA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - covid_1
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - covid_2
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - covid_3
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - covid_4
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Labor
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Lunar
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Summer
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                /v////ORAEE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AQAAAAAAAAA=
          - - deaths
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                AAAAAABAW0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - cases
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                wczMzIw8ykA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - covid_1
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - covid_2
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - covid_3
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - covid_4
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Labor
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Lunar
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Summer
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object/apply:collections.OrderedDict
- - - deaths
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
  - - cases
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  global_local: global
  mode: multiplicative
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: 33
        condition_name: null
        period: 365.25
        resolution: 33
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: 25
        condition_name: null
        period: 7
        resolution: 25
  reg_lambda: 0.004931976152481779
  weekly_arg: 25
  yearly_arg: 33
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 142
  lambda_delay: 71
  learning_rate: 9.906283367308491
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 1.0
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 2894
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 8
    - *id001
    - false
    - !!binary |
      A/HyTMK/5D/wqWW4iKjlP9ZD6jcyS+Y/niItda/+5j/lYStp0EboPylMY5sb/eg/l6QaUD5R6T/E
      fZ3DCDzrPw==
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 8
  trend_global_local: global
  trend_reg: 0.006723113307749288
  trend_reg_threshold: null
d_hidden: null
id_list:
- __df__
max_lags: 28
meta_used_in_model: false
metrics:
  MAE: !!python/object:torchmetrics.regression.mae.MeanAbsoluteError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDQAAADIyNDE0Mzk1MjQ4MzJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMjQx
          NDM5NTI0ODMycQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgNAAAAMjI0MTQzOTUyNTIxNnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDQAAADIyNDE0
          Mzk1MjUyMTZxAWEuAQAAAAAAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_abs_error: false
      total: false
    _reductions:
      sum_abs_error: &id004 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id004
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADIyNDE0Mzk1MjgxOTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMjQx
        NDM5NTI4MTkycQFhLgEAAAAAAAAAAAAAAA==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgNAAAAMjI0MTQzOTUyNjE3NnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDQAAADIyNDE0
        Mzk1MjYxNzZxAWEuAQAAAAAAAAAAAAAAAAAAAA==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
  RMSE: !!python/object:torchmetrics.regression.mse.MeanSquaredError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDQAAADIyNDE0Mzk1MjgwMDBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMjQx
          NDM5NTI4MDAwcQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgNAAAAMjI0MTQzOTUyMzI5NnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDQAAADIyNDE0
          Mzk1MjMyOTZxAWEuAQAAAAAAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_squared_error: false
      total: false
    _reductions:
      sum_squared_error: *id004
      total: *id004
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    squared: false
    sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADIyNDE0Mzk1MjY0NjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMjQx
        NDM5NTI2NDY0cQFhLgEAAAAAAAAAAAAAAA==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgNAAAAMjI0MTQzOTUyNzEzNnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDQAAADIyNDE0
        Mzk1MjcxMzZxAWEuAQAAAAAAAAAAAAAAAAAAAA==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
n_forecasts: 1
n_lags: 28
num_hidden_layers: 0
num_seasonalities_modelled: 1
num_trends_modelled: 1
